/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectocajeroutn;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author William
 */
public class FormIngreso extends javax.swing.JFrame {

    /**
     * Creates new form FormIngreso
     */
    
    //private Cuentas[] cuentas;
    public  int numeroCuenta;
   
    public static int numeroUsuario ;
    
    public FormIngreso() {
        initComponents();
        lblNuevaContrasenia.setVisible(false);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jtextNumeroCuenta = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblNuevaContrasenia = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JtextContrasenia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 255));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Numero Cuenta");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectocajeroutn/log_logout_door_1563.png"))); // NOI18N
        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jtextNumeroCuenta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtextNumeroCuentaFocusGained(evt);
            }
        });
        jtextNumeroCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtextNumeroCuentaMouseClicked(evt);
            }
        });
        jtextNumeroCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextNumeroCuentaActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectocajeroutn/Cancel_icon-icons.com_73703.png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        lblNuevaContrasenia.setForeground(new java.awt.Color(204, 204, 204));
        lblNuevaContrasenia.setText("Establecer nueva contrasenia");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Contraseña");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblNuevaContrasenia))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JtextContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNuevaContrasenia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(JtextContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtextNumeroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtextNumeroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(21, 21, 21)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectocajeroutn/loginmanager_10029.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtextNumeroCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextNumeroCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextNumeroCuentaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //mayusculaMinuscula(jtextNumeroCuenta.getText());
        try {
                jtextNumeroCuenta.setText(jtextNumeroCuenta.getText().trim());
                if( validarCuenta(Integer.parseInt(jtextNumeroCuenta.getText().trim()), JtextContrasenia.getText().trim())){
                new Menu_principal().setVisible(true);              
                this.dispose();               
            }
            
        }catch(NumberFormatException e ){
            JOptionPane.showMessageDialog(null, "La cuenta está conformada por solo numeros\nRevisa tu numero de cuenta \n"  + e);
        }      
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private boolean mayusculaMinuscula(String cad ){
        lblNuevaContrasenia.setVisible(true);
        char[] letras;
        //letras = new char[cad.length()];
        letras = cad.toCharArray();
        boolean minuscula = false;
        boolean mayuscula = false;
        for (int i = 0; i < cad.length() ; i++) {
            if (Character.isUpperCase(letras[i])) {
                mayuscula = true;
            }else if (Character.isLowerCase(letras[i])) {
                minuscula = true;
            }
        }
        if (mayuscula && minuscula) {
            return true;
        }
        return false; 
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jtextNumeroCuenta.setText("");
        JtextContrasenia.setText("");
        System.exit(0);
        //JOptionPane.showMessageDialog(this,"Vuelva a escribir su usuario y contraseña");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtextNumeroCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtextNumeroCuentaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextNumeroCuentaMouseClicked

    private void jtextNumeroCuentaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtextNumeroCuentaFocusGained
        // TODO add your handling code here:
        lblNuevaContrasenia.setVisible(false);
    }//GEN-LAST:event_jtextNumeroCuentaFocusGained

    private boolean validarCuenta(int numeroCuenta, String contrasenia){
        boolean numeroCuentaValido = true ;
        if (contrasenia.length() <8) {
            JOptionPane.showMessageDialog(null, "La longitud de la contrasenia es menor a 8\nVuelve a ingresarla");
            return false;
        }        
        for (int i = 0; i < 5; i++) {
           
            if (ProyectoCajeroUTN.cuentas[i].getNumeroCuenta() == numeroCuenta) {
                if (contrasenia.equals(ProyectoCajeroUTN.cuentas[i].getContrasenia())) {
                    JOptionPane.showMessageDialog(this, "Bienvenido");                    
                    numeroUsuario= i;
                    return true;
                }else if ("-".equals(ProyectoCajeroUTN.cuentas[i].getContrasenia())) {
                     lblNuevaContrasenia.setVisible(true);                     
                    if(mayusculaMinuscula(contrasenia)){
                        
                         try {
                             if (alterNumChar(contrasenia)) {
                                 ProyectoCajeroUTN.cuentas[i].setContrasenia(contrasenia);                                
                                 numeroUsuario= i;
                                 JOptionPane.showMessageDialog(null, "La contraseña se ha modificado \nLa proxima vez se usara la ingresada");
                                 return true;
                             }else{
                                 
                                 return false;                       
                             }
                         } catch (Exception ex) {
                             JOptionPane.showMessageDialog(null, ex);
                         }                        
                    }else{
                        JOptionPane.showMessageDialog(this, "Ingresa una contrasenia que contenga por lo menos \n una letra"
                                + " mayuscula y una minuscula");
                    }
                    return false;
                }
                else{
                    JOptionPane.showMessageDialog(this, "Contrasenia Incorrecta");
                }
            }else{
               numeroCuentaValido = false;
            }
        }
        if (!numeroCuentaValido) {
            JOptionPane.showMessageDialog(this, "Cuenta no valida \n Vuelve a ingresar los datos");
        }
        return false;        
    }
    private boolean alterNumChar(String cad) throws Exception{
        lblNuevaContrasenia.setVisible(true);
        char[] letras; // creamos un nuevo vector de char, para poder recorrer nuesto string
       
        letras = cad.toCharArray(); // convertimos el string un arreglo de chars
        boolean letra = false;
        boolean numero = false;
        if (Character.isDigit(letras[0])) {
            numero=true;           
        }else if( Character.isLetter(letras[0]) ){            
            letra = true;
        }else{
            throw new Exception( "Ingresa letras o numero por favor" );
            
        }        
        for (int i = 1; i < cad.length() ; i++) {
            if (Character.isDigit(letras[i]) && letra  && !numero) {
                numero = true;
                letra = false;
            }else if (Character.isLetter(letras[i]) && !letra  && numero) {
                letra = true;
                numero = false;
            }else{
                throw new Exception( " Alterna solo entre numero y letras por favor, no consecutivos" );                
            }
        }        
        if (letra !=  numero) {
            return true;
        }else{
            throw new Exception( "Alterna entre numero y letras por favor " );
            
        }        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormIngreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JtextContrasenia;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jtextNumeroCuenta;
    private javax.swing.JLabel lblNuevaContrasenia;
    // End of variables declaration//GEN-END:variables
}
